# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- recent_posts
- tagcloud
- archive

# Miscellaneous
google_analytics: UA-43935113-3
favicon: /favicon.ico
twitter: coolwuxing
google_plus:
fb_admins:
fb_app_id: